networks:
  1panel-network:
    external: true
services:
  mongodb:
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: 0
          memory: 0
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${PANEL_DB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${PANEL_DB_ROOT_USER}
    image: mongo:8.2.3
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:27017
    restart: always
    volumes:
      # 数据持久化目录
      - ./mongo-data:/data/db
      # 映射证书目录 (宿主机路径 : 容器内路径)
      - /data/mongo_ssl:/etc/ssl/mongo
    command: >
      --tlsMode requireTLS
      --tlsCertificateKeyFile /etc/ssl/mongo/mongodb.pem
